### ISSUE TITLE
Ordering of results for Allergic Rhinitis needs f() validation (was: Results never load when clicking on treats edge)

### ISSUE THREAD

**Issue by khanspers** [NCATSTranslator/Feedback#192]
Query : What drugs may treat seasonal allergic rhinitis?

Clicking on the treats edge for any of the results (for example Cetirizine, listed as #6, with 38 publications), the resulting evidence never loads. The wheel keeps spinning indefinitely and the message says "Calculating".

http://transltr-bma-ui-dev.ncats.io/results?l=Seasonal%20Allergic%20Rhinitis&t=0&q=3b09b5df-1b95-4ca8-b78e-23d1ce420731

About the results in general: Folic Acid is listed with a higher score (one publication) than Loratadine and Cetirizine (38/44 publications), which is a bit weird. Looking at the results in ARAX it looks like its coming from BTE (textmining).

**Comment by sierra-moxon** [comment]
retested today on CI:
https://ui.ci.transltr.io/results?l=Seasonal%20Allergic%20Rhinitis&i=MONDO:0005324&t=0&q=51f86eb9-f483-40f6-9d19-2bae406be025

- evidence loads consistently and correctly.
- 272 results return immediately 
- it continues to be unclear why Folic Acid (1 pub) has a higher score than Loratadine (many pubs)

I think the best course of action here is to change the assignees.  The UI is fixed; the ordering is still unclear.  @Rosinaweber - is this a good test case for the f-score work you are doing? 


![Image](https://github.com/NCATSTranslator/Feedback/assets/4561292/e53c8e2d-de71-4b6b-8853-abfc28536cfa)

**Comment by Rosinaweber** [comment]
Thanks, @sierra-moxon . It might be. Checking now...

**Comment by sharatisrani** [comment]
Problems not all solved - result #6 then, could not load evidence.  Score was 98.5, now 42 - still cannot see the pubs.  Will follow with @Genomewide

**Comment by sharatisrani** [comment]
@Rosinaweber received benchmarks from @suihuang-ISB on Allergic Rhinitis, now checking.

**Comment by sierra-moxon** [comment]
hi @sharatisrani - is this still a show-stopper?

**Comment by Rosinaweber** [comment]
Hi @sierra-moxon: 
Sui prepared estimates for this use case and we are currently preparing to bring this to the next O&O for discussion. As soon as we obtain some feedback on the ordering weights based on this, this should be adjusted, but it is still work in progress. Thanks.

**Comment by sierra-moxon** [comment]
from TAQA:
Rosina: using this as a benchmark in testing the scoring.  Catagories of drugs would be helpful, they have been created.

**Comment by sierra-moxon** [comment]
from TAQA:
- we can't really think of things to expose that explain the logic of the order more than the doc we've put in place. 
- this is really hard - need an expert panel?  
- we can use our benchmarks to see how this answer changes over time.  <-- this is our technical solution.  
- we also need to decrease our focus on treats in the coming year. 


Closing for now.
