### ISSUE TITLE
NamedThings in search results that are tagged in NN as more specific typed entities

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/Feedback#214]
Why do some of these some back as NamedThing:

https://ui.test.transltr.io/results?l=Multiple%20Sclerosis&t=0&q=bc963cad-e2e3-4200-b401-d757597b4766

https://arax.ci.transltr.io/?r=bc963cad-e2e3-4200-b401-d757597b4766

![image](https://github.com/NCATSTranslator/Feedback/assets/38321826/ba64b5a7-75b9-4f8b-a378-6edd2245c63c)

The first result is Avonex which is in nodenorm as many types:

{
  "UMLS:C0594372": {
    "id": {
      "identifier": "UMLS:C0594372",
      "label": "Avonex"
    },
    "equivalent_identifiers": [
      {
        "identifier": "UMLS:C0594372",
        "label": "Avonex"
      },
      {
        "identifier": "UMLS:C0752980",
        "label": "Rebif"
      },
      {
        "identifier": "UMLS:C0982234",
        "label": "Recombinant interferon beta-1a"
      },
      {
        "identifier": "UMLS:C1522588",
        "label": "BG9418"
      }
    ],
    "type": [
      "biolink:Polypeptide",
      "biolink:BiologicalEntity",
      "biolink:NamedThing",
      "biolink:Entity",
      "biolink:GeneProductMixin",
      "biolink:ChemicalEntityOrGeneOrGeneProduct",
      "biolink:ChemicalEntityOrProteinOrPolypeptide",
      "biolink:ThingWithTaxon",
      "biolink:GeneOrGeneProduct",
      "biolink:MacromolecularMachineMixin",
      "biolink:Protein"
    ]
  }
}

**Comment by sierra-moxon** [comment]
Avonex
UMLS:C0982234

**Comment by sierra-moxon** [comment]
from TAQA:
Avonex is brand name; this is possibly unethical, the real drug is Recombinant interferon beta-1aSNG001
also produce endogenously - will also have this as a gene, it is a polypeptide, it is also a drug. 
 - we likely can't fix this - we just need two nodes, one for the drug one for the polypeptide/gene

many issues here:
NN types are not getting into either UI (neither ARAX nor UI).  We think the most specific category should be returned (could be a fixed issue).  
We need to get conflation in there between drug and small molecule, then  Recombinant interferon beta-1aSNG001 should some back.

**Comment by sierra-moxon** [comment]
from TAQA:
could the UI team please describe how the category comes back in the UI path representation?

**Comment by sierra-moxon** [comment]
from TAQA:
improving showing influenza -- we need to replace ChEMBL with clinicaltrials.gov

**Comment by tokebe** [comment]
Hi, we've looked at this from the BTE end and have concluded that BTE returning NamedThing was caused by a change in NodeNormalizer's behavior: Where it previously returned a type array sorted most->least specific, it now returns a type array sorted least->most specific, at least for all nodes that BTE returned with `NamedThing` as the category.

**Comment by gaurav** [comment]
This should now be fixed in NodeNorm at https://nodenormalization-sri.renci.org/docs -- see e.g. https://nodenormalization-sri.renci.org/1.3/get_normalized_nodes?curie=UMLS%3AC0594372&conflate=true, which now correctly lists biolink:Protein as the most specific Biolink class, rather than [biolink:Polypeptide on ITRB Prod](https://nodenorm.transltr.io/1.3/get_normalized_nodes?curie=UMLS%3AC0594372&conflate=true).

Once @YaphetKG approves PR https://github.com/helxplatform/translator-devops/pull/679, it should also be pushed to ITRB Dev. Once we've tested both instances to make sure that they're running correctly, I'll put in a request to update ITRB Prod.

**Comment by sstemann** [comment]
@sierra-moxon the starter topic of this issue seems resolved - in Test on 7/14, i no longer see named thing as a node type.  

<img width="899" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/cd4788c5-8b70-4a20-973a-32d5186f5627">

I do still see Influenza Vaccine as a treatment for MS - perhaps this needs its own ticket for Improve and BTE, i'm not sure it's actually related to the root of this ticket.

for the facets - indications, i'm not sure what you are looking for here, i think the facets are fine?

for the score  - i think this is a question for the ARAs and O&O

<img width="882" alt="image" src="https://github.com/NCATSTranslator/Feedback/assets/38321826/d9f29f7a-03d4-40bb-8ce0-d0b8a22fe99b">
