### ISSUE TITLE
NN failures: JAK genes

### ISSUE THREAD

**Issue by cbizon** [NCATSTranslator/Feedback#821]
Query: What genes are downed by Ruxolitinib?

PK: ab417e9e-cac8-45c8-a114-4f4d4514c038

We get results for JAK1, JAK2, and JAK3, but also at least "Janus Kinase 1" and "Janus Kinase 2".

It looks like the UMLS identifiers (e.g. UMLS:C0169661) are not merging with the other gene/protein ids.

**Comment by gaurav** [comment]
I've confirmed that UMLS:C0169661 "Janus kinase 2" is being included by the protein module, not the leftover UMLS module. It really should be combined with UniProtKB:A8K910 "A8K910_HUMAN Tyrosine-protein kinase (trembl)" and UniProtKB:O60674 "JAK2_HUMAN Tyrosine-protein kinase JAK2 (sprot)" (which is not currently the case: https://nodenorm.ci.transltr.io/1.5/get_normalized_nodes?curie=NCBIGene%3A3717&curie=UMLS%3AC0169661&conflate=true&drug_chemical_conflate=false&description=false). I think this is another case of proteins and chemicals not being properly combined (https://github.com/TranslatorSRI/Babel/issues/310), so diagnosing and fixing that issue should fix this as well. Assigning to Guppy.

**Comment by gaurav** [comment]
FWIW we _do_ combine [UMLS:C1527617 "JAK2 protein, human"](https://uts.nlm.nih.gov/uts/umls/concept/C1527617) with the other protein identifiers, but not [UMLS:C0169661 "Janus kinase 2"](https://uts.nlm.nih.gov/uts/umls/concept/C0169661), which we have both as its own clique as a protein [as well as in a ChemicalEntity clique](https://nodenorm.ci.transltr.io/1.5/get_normalized_nodes?curie=NCBIGene%3A3717&curie=UMLS%3AC0169661&curie=MESH%3AD053614&conflate=true&drug_chemical_conflate=false&description=false) with MESH:D053614 "Janus Kinase 2". So even once we close https://github.com/TranslatorSRI/Babel/issues/310, there will be a bit left over as to why MESH:D053614 isn't being merged with the other JAX2 proteins.

**Comment by gaurav** [comment]
Pushing the chemical/protein issue to Hammerhead.

**Comment by sstemann** [comment]
this is still a problem in Hammerhead

https://ui.test.transltr.io/results?l=Ruxolitinib%20Phosphate&i=CHEBI:66917&t=4&r=0&q=6f79bab3-c6b8-43d7-a4b6-8a27e167ba82

![image](https://github.com/user-attachments/assets/b7d2c4ae-767f-4fd8-b64c-f9e9e11ecf1b)
