### ISSUE TITLE
Type-ahead wonky. Would have thought atherosclerosis would have been a top result from such a service.

### ISSUE THREAD

**Issue by TranslatorIssueCreator** [NCATSTranslator/Feedback#85]
## Steps to reproduce:
Trying to remember how to spell atherosclerosis ... the type ahead is good. But initial results for 'Athe' or 'Ather' don't give anything other than Arterial Fatty at first. And then I tried capturing the details for this bug report and it stopped giving me any type-ahead. https://nodenorm.transltr.io/1.3/get_normalized_nodes POST gave me 503 Service Temporarily Unavailable
nginx

**Comment by sierra-moxon** [comment]
see also #42

**Comment by dnsmith124** [comment]
The core issue here appears to be that when search terms have relatively few characters, many terms are returned by the NR and NN, but many of them are not diseases (and in some cases, most of them), and so are filtered out. This results in relatively few results shown to the user for terms that seem like they should instead return many results. 

I've implemented the following changes in the develop branch to try to address this particular issue:
- increased number of results that the autocomplete requests from the name resolver from 40 to 100
- clamped the number of results that can display to the user to 40 to keep the autocomplete window parsable by the user

This should give the user more of a chance to get the disease they want in their 'unspecific' search term!

**Comment by sierra-moxon** [comment]
tested "ath" and "ather" on https://ui.test.transltr.io/ -- both return some form of "Atherosclerosis" 👍 :).  However, its not immediately clear the difference between "Atherosclerosis" and "Atherosclerosis susceptibility" ("ath" returns "Atherosclerosis susceptibility" and "ather" returns  Atherosclerosis" but only "Atherosclerosis" returns any results. "Atherosclerosis susceptibility" just spins (I gave up after 4 mins).  


![Image](https://user-images.githubusercontent.com/4561292/214964681-e8eb4c9b-0f09-44ba-b556-f7ba9b40fe28.png)


![Image](https://user-images.githubusercontent.com/4561292/214964685-8bd0f33d-9f22-4f4f-b067-8340c33f97ef.png)

Maybe no autocomplete request should be sent unless a minimum number of characters is entered (e.g. more than 4, 5)?

- [ ] need to figure out why "Atherosclerosis susceptibility" does not return any results but is included in the autocomplete.  (might be there is no synonym/xref/mapping(?) in MONDO to this term, which may be from UMLS?)

**Comment by sierra-moxon** [comment]
from TAQA:
- users that try very common text strings (and short ones), get thousands of results and no disease.  
- step one: get a curie, step two: get a canonical name from NameResolver - sometimes this name is nowhere near what the user asked for.

**Comment by sierra-moxon** [comment]
Gaurav: yep, NameRes filter by biolink type now an issue at https://github.com/TranslatorSRI/NameResolution/issues/39

Second issue not solved: matching at NodeNorm returning different things.  UI to show synonyms? - yep.  Sometimes this is a "feature" for users to use old names.

**Comment by sstemann** [comment]
UI team is also working on fixes for this issue

**Comment by gaurav** [comment]
We should be able to eliminate all of these issues once we deploy the new NameRes (currently being rebuilt, with about 10 hours remaining). The current dev NameRes is sorting atherosclerosis disorder below a bunch of other atherosclerosis-related MONDOs (see http://name-resolution-sri-dev.apps.renci.org/lookup?string=Athe&offset=0&limit=10&biolink_type=Disease&only_prefixes=MONDO%7CHP), but that’s exactly what this rebuild hopes to fix.

**Comment by gaurav** [comment]
Definitely looking better with the current NameRes with filtering:

| Search term | Notes |
| ------------ | ------ |
| [`athe`](http://name-resolution-sri-dev.apps.renci.org/lookup?string=Athe&offset=0&limit=10&biolink_type=Disease&only_prefixes=MONDO%7CHP) | atherosclerosis (MONDO:0005311) is the third result |
|  [`ather`](http://name-resolution-sri-dev.apps.renci.org/lookup?string=Ather&offset=0&limit=10&biolink_type=Disease&only_prefixes=MONDO%7HP) | atherosclerosis (MONDO:0005311) is the second result after atherosclerosis susceptibility (MONDO:0007169). |
| [`atherosclerosis`](http://name-resolution-sri-dev.apps.renci.org/lookup?string=Ather&offset=0&limit=10&biolink_type=Disease&only_prefixes=MONDO%7HP) | atherosclerosis (MONDO:0005311) finally becomes the first result. We've seen this before (https://github.com/TranslatorSRI/NameResolution/issues/85) and are trying to work out a solution, but having atherosclerosis as the second result isn't too bad IMO. |

I'll track this and close it after the new NameRes have been successfully incorporated into the UI.

**Comment by gglusman** [comment]
I just tried it on test. For 'athe', atherosclerosis was the 3rd option. For 'ather', it was the first one.

**Comment by gaurav** [comment]
We're now back to `atherosclerosis susceptibility` staying as the top result until you get to `atherosclerosis`, when it finally becomes the first result. In order to improve gene results, we're hoping to sort by CURIE suffix (in this case, 0007169 vs 0005311) between identically scoring results, which might boost `atherosclerosis` to the top. Otherwise, I think it would be acceptable to close this issue as `atherosclerosis` in second place isn't too bad. What do y'all think?
